version: '3'

services:
  mysql-db:
    image: mysql:8.0
    container_name: gainge-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_NAME}
      MYSQL_DATABASE: ${DATABASE_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptest"]
      interval: 5s
      retries: 10
      timeout: 3s

volumes:
  mysql-data: